{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockative/3.0.2/mockative-3.0.2.module",
    "group": "io.github.mohamadjaara",
    "module": "mockative",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-linuxArm64Main-3.0.2.klib",
          "url": "mockative-linuxarm64-3.0.2.klib",
          "size": 114840,
          "sha512": "d963cfeb7365f51e5fd74b425570a6412fc093dfac09abdff7a8e8d47936bc247c1f2daa70274f3edc835f73412091cdc64c5dd4b2e1160869b8fc3f21913c39",
          "sha256": "c8369c3c209e3fd96fadcd96aa8cd22e5333a339422a660bd11904afcdddd8b9",
          "sha1": "df58e984ed705af6fa9def8286a6ef4b8f937933",
          "md5": "8401bf1c01bf5e287b9e96855a39bc41"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mockative-linuxarm64-3.0.2-sources.jar",
          "url": "mockative-linuxarm64-3.0.2-sources.jar",
          "size": 26608,
          "sha512": "b4ac6c450e576befb94a4267ed010f07f4c447379b53b1206409fc46e9da80712529caa31744f6925b34e90e042c896316b7ebf78a2497ffe340acfac8ae542f",
          "sha256": "812750547df1ca7a8a74577d621ca69d8960aabb07de4c19716b6e3fca7cbdac",
          "sha1": "ebad7076aef4e9fce66c6dd80426f13ba4b82750",
          "md5": "9e102d1341eb4f34e6ba7981d7cff88d"
        }
      ]
    }
  ]
}
