{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockative/3.0.2/mockative-3.0.2.module",
    "group": "io.github.mohamadjaara",
    "module": "mockative",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-watchosSimulatorArm64Main-3.0.2.klib",
          "url": "mockative-watchossimulatorarm64-3.0.2.klib",
          "size": 114919,
          "sha512": "c2d0f9cd284239cdd6f22976720721f5cfd2e68407f260fca7fc1fb898d4f1e9ebc21e4c2f06cee401b8608d04c49877f8e46f92f42d896e85a7d77d379feb26",
          "sha256": "4a5a9ec382f8ccda7d6fb94302b2182e1749e007ddb13f5535f22912f2ca4f5c",
          "sha1": "e9b69cb64e2a2dd41bc1f244d440be735422905a",
          "md5": "dd521fef13b6b4647a27111d21047b25"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mockative-watchossimulatorarm64-3.0.2-sources.jar",
          "url": "mockative-watchossimulatorarm64-3.0.2-sources.jar",
          "size": 26608,
          "sha512": "b4ac6c450e576befb94a4267ed010f07f4c447379b53b1206409fc46e9da80712529caa31744f6925b34e90e042c896316b7ebf78a2497ffe340acfac8ae542f",
          "sha256": "812750547df1ca7a8a74577d621ca69d8960aabb07de4c19716b6e3fca7cbdac",
          "sha1": "ebad7076aef4e9fce66c6dd80426f13ba4b82750",
          "md5": "9e102d1341eb4f34e6ba7981d7cff88d"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-watchossimulatorarm64-3.0.2-metadata.jar",
          "url": "mockative-watchossimulatorarm64-3.0.2-metadata.jar",
          "size": 261,
          "sha512": "d84fed4476c387785f762c2ba415687696b0c4218922c4e2dcf3a056d02083dc38d61f4a6a794f2cdf3a88748f273c3e21c9268ca47bd7bd8c97b4b8f8cf083e",
          "sha256": "daef5b1345f5e6dcadc9d1dc8356c212b7b011593b6fd6832595336e9d9dbe48",
          "sha1": "033441c8965465d6c22f12547037dab0f203634d",
          "md5": "d0ba6d2b3ee06517b19d45b242aeefa4"
        }
      ]
    }
  ]
}
