{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockative/3.0.2/mockative-3.0.2.module",
    "group": "io.github.mohamadjaara",
    "module": "mockative",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-tvosSimulatorArm64Main-3.0.2.klib",
          "url": "mockative-tvossimulatorarm64-3.0.2.klib",
          "size": 114898,
          "sha512": "abda189531f0007a20b4052d134a9d0126added27c0c3cf47d076ec05868f5c8dbacb9dfb7fc0b80052cc1b696de2cf1c93e64d5a34d40c0e95b4dd62d58de2c",
          "sha256": "9c0cc30c6eeb5d53db3ef6a21b686b73941e6b0daa0da4121e8723df76a2a383",
          "sha1": "07682de6c24874d9a92281484d97bc3320f2db33",
          "md5": "032aa11c22469d9cc46a737fd0fd5d28"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mockative-tvossimulatorarm64-3.0.2-sources.jar",
          "url": "mockative-tvossimulatorarm64-3.0.2-sources.jar",
          "size": 26608,
          "sha512": "b4ac6c450e576befb94a4267ed010f07f4c447379b53b1206409fc46e9da80712529caa31744f6925b34e90e042c896316b7ebf78a2497ffe340acfac8ae542f",
          "sha256": "812750547df1ca7a8a74577d621ca69d8960aabb07de4c19716b6e3fca7cbdac",
          "sha1": "ebad7076aef4e9fce66c6dd80426f13ba4b82750",
          "md5": "9e102d1341eb4f34e6ba7981d7cff88d"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-tvossimulatorarm64-3.0.2-metadata.jar",
          "url": "mockative-tvossimulatorarm64-3.0.2-metadata.jar",
          "size": 261,
          "sha512": "d0aefbea7ae510fbcc3e692c594780d97c3ee5167fcfd697c3fbf22de91dbeab726a8a396f491bfb0277b20a7ee12bb441c45419871a421f507f3bcda172f2bf",
          "sha256": "8a5ac7c9546ff29d892a32a71e7c394c919e2910f2bb4f669f16704447115665",
          "sha1": "4f5b64855b6df35513c1ab99346e2b40df5b5a45",
          "md5": "1e417cb6eda81474e2e3b3f6f095f616"
        }
      ]
    }
  ]
}
