{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockative/3.0.2/mockative-3.0.2.module",
    "group": "io.github.mohamadjaara",
    "module": "mockative",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-linuxX64Main-3.0.2.klib",
          "url": "mockative-linuxx64-3.0.2.klib",
          "size": 114828,
          "sha512": "78c85fd797e481824e73aecf0392ff6be3d363860a25923d0c10af27766cd93fdfa146c2095afca45b86d332eed96c9968c152788261c0eccb016ef0c0994365",
          "sha256": "cc45de0a8ea4b83d58826ee7879b96f948b91125f62c2848ea7f4347950a8dd5",
          "sha1": "7133b4039466ed80ed4aabcc20444f9444ef07ea",
          "md5": "e3815a5056bcd7f1178fc095e1cb2a1d"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mockative-linuxx64-3.0.2-sources.jar",
          "url": "mockative-linuxx64-3.0.2-sources.jar",
          "size": 26608,
          "sha512": "b4ac6c450e576befb94a4267ed010f07f4c447379b53b1206409fc46e9da80712529caa31744f6925b34e90e042c896316b7ebf78a2497ffe340acfac8ae542f",
          "sha256": "812750547df1ca7a8a74577d621ca69d8960aabb07de4c19716b6e3fca7cbdac",
          "sha1": "ebad7076aef4e9fce66c6dd80426f13ba4b82750",
          "md5": "9e102d1341eb4f34e6ba7981d7cff88d"
        }
      ]
    }
  ]
}
