{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockative/3.0.2/mockative-3.0.2.module",
    "group": "io.github.mohamadjaara",
    "module": "mockative",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-iosArm64Main-3.0.2.klib",
          "url": "mockative-iosarm64-3.0.2.klib",
          "size": 114826,
          "sha512": "03aacb25287ebc6f6723842939e32e9a1a540e7fbe579fb0e40ff6e2049b3402edeac55d70680863bd9be0076c10775ff67c9e180bdb29539102aa8123b61c76",
          "sha256": "e6438e5f8bfcd31b9a38af0aa7b2c825163ed4e63d4bfbfc9e880b50f355c7cf",
          "sha1": "ce516e1efef61b9080a836f7f6643429666e8d74",
          "md5": "38619f1d4ecf210f9636244834fac5ee"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mockative-iosarm64-3.0.2-sources.jar",
          "url": "mockative-iosarm64-3.0.2-sources.jar",
          "size": 26608,
          "sha512": "b4ac6c450e576befb94a4267ed010f07f4c447379b53b1206409fc46e9da80712529caa31744f6925b34e90e042c896316b7ebf78a2497ffe340acfac8ae542f",
          "sha256": "812750547df1ca7a8a74577d621ca69d8960aabb07de4c19716b6e3fca7cbdac",
          "sha1": "ebad7076aef4e9fce66c6dd80426f13ba4b82750",
          "md5": "9e102d1341eb4f34e6ba7981d7cff88d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-iosarm64-3.0.2-metadata.jar",
          "url": "mockative-iosarm64-3.0.2-metadata.jar",
          "size": 261,
          "sha512": "6c49bdaf42e2b0157d6c5ba43a422fc4a719af523959ed5d4070c6c6f2c6451cd34a945fe1bc6362a9f98d8086e911bc2c307867f2a1e11e25a21ee9eb7b9ea1",
          "sha256": "d0d86ef19bf7027d31a42e0f69689e70f4706076db763655fad73341b02a7891",
          "sha1": "1deddff8aba96755d42d9da314ea703e2b78d8b8",
          "md5": "5c5814adefc12b7be29e845e1a67d27a"
        }
      ]
    }
  ]
}
